// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using FinalApp.Models;
//
//    var cognitiveServicesResponse = CognitiveServicesResponse.FromJson(jsonString);

namespace FinalApp.Models {
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using J = Newtonsoft.Json.JsonPropertyAttribute;
    using R = Newtonsoft.Json.Required;
    using N = Newtonsoft.Json.NullValueHandling;

    public partial class CognitiveServicesResponse {
        [J("status")] public string Status { get; set; }
        [J("recognitionResult", NullValueHandling = N.Ignore)] public RecognitionResult RecognitionResult { get; set; }
    }

    public partial class RecognitionResult {
        [J("lines")] public Line[] Lines { get; set; }
    }

    public partial class Line {
        [J("boundingBox")] public long[] BoundingBox { get; set; }
        [J("text")] public string Text { get; set; }
        [J("words")] public Word[] Words { get; set; }
    }

    public partial class Word {
        [J("boundingBox")] public long[] BoundingBox { get; set; }
        [J("text")] public string Text { get; set; }
        [J("confidence", NullValueHandling = N.Ignore)] public string Confidence { get; set; }
    }

    public partial class CognitiveServicesResponse {
        public static CognitiveServicesResponse FromJson(string json) => JsonConvert.DeserializeObject<CognitiveServicesResponse>(json, FinalApp.Models.Converter.Settings);
    }

    public static class Serialize {
        public static string ToJson(this CognitiveServicesResponse self) => JsonConvert.SerializeObject(self, FinalApp.Models.Converter.Settings);
    }

    internal static class Converter {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
